# Generated by Django 4.2.1 on 2023-06-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_brand_name_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brand'),
        ),
    ]
